apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      server: dumb-server
  template:
    metadata:
      labels:
        server: dumb-server
    spec:
      containers:
        - name: fake-server-pod
          image: stephanrotolante/service-deployment
          ports:
            - containerPort: 8080